{% set name = "backports.csv" %}
{% set version = "1.0.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1277dfff73130b2e106bf3dd347adb3c5f6c4340882289d88f31240da92cbd6d

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >3.3
    - pip
  run:
    - python

test:
  imports:
    - backports.csv

about:
  home: https://github.com/ryanhiebert/backports.csv/
  license: PSFL 2
  license_file: LICENSE.rst
  summary: 'Backport of Python 3's csv module for Python 2'

extra:
  recipe-maintainers:
    - rmax
    - oblute
    - benhuff
